sudo: required
services:
  - docker

before_install:
  - docker build -t adarsh2day/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adarsh2day/react-test npm run test 

after_success:
  - docker build -t adarsh2day/multi-client ./client
  - docker build -t adarsh2day/multi-nginx ./nginx
  - docker build -t adarsh2day/multi-server ./server
  - docker build -t adarsh2day/multi-worker ./worker

  # Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take images and push them to docker hub
  - docker push adarsh2day/multi-client
  - docker push adarsh2day/multi-nginx
  - docker push adarsh2day/multi-server
  - docker push adarsh2day/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app:  multi-docker
  env:  MultiDocker-env 
  bucket_name:  elasticbeanstalk-eu-central-1-759161019306
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secreat_access_key:
    secure: $AWS_SECRET_KEY